apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: venkatgurram/pro:v5
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-svc
spec:
  selector:
     app: my-app
  type: NodePort
  ports:
  - targetPort: 3000
    port: 80
    protocol: "TCP"
